### ISSUE TITLE
ai모델을 사용한 이미지 검색 api 응답 형태 변경, 복합 재질인 경우도 검색할 수 있도록

### ISSUE THREAD

**Issue by hoiae** [D0ri123/foreco#136]
## 📌Feature Issue
> api응답 형태 변경
## 📝To-do
- [x] api응답 형태 변경

## ETC
> 기존 api/v1/image 의 응답값의 id는 조회가 가능한지 아닌지를 나타내는 -1 or 구체적인 id였지만,  ai모델에서 분석한 모든 키워드 별로 id를 반환하도록 수정했습니다. !

**Comment by D0ri123** [comment]
@hoiae 엇 이건 어떤 부분 때문에 다시 변경하시나요??

**Comment by hoiae** [comment]
> ## 📌Feature Issue
> > api응답 형태 변경
> 
> ## 📝To-do
> * [ ]  api응답 형태 변경
> 
> ## ETC
> >



> @hoiae 엇 이건 어떤 부분 때문에 다시 변경하시나요??

아! 복합 재질인 경우에도 클라이언트에서 여러개를 보여준다음에 상세조회할 수 있도록 응답형태를 수정했습니다. 기존에는 1차 평가 기준에 맞추려고 단일 재질인 경우에만 id를 구체적으로 한개 반환했었습니다~!

**Comment by D0ri123** [comment]
네네 확인했습니다!! 고생하셨어요!👏
